### ISSUE TITLE
Ruby-build doesn't update automatically

### ISSUE THREAD

**Issue by cyrusstoller** [cyrusstoller/gardenbed#47]
Hopefully this will be resolved soon.

https://github.com/alup/puppet-rbenv/issues/112

If not, it may be worth switching to https://github.com/justindowning/puppet-rbenv

**Comment by sman591** [comment]
Is a switch to [justindowning/puppet-rbenv](https://github.com/justindowning/puppet-rbenv) difficult to complete?

**Comment by cyrusstoller** [comment]
It shouldn't be too bad. I just want to be sure to keep the hiera data the same. Thanks for reminding me to look into this.
