### ISSUE TITLE
Binstubs aren't available in production

### ISSUE THREAD

**Issue by sman591** [cyrusstoller/gardenbed#49]
If I'm not mistaken, binstubs should be available in production? I followed the instructions on the [blog post](http://www.cyrusstoller.com/2014/12/23/deploying-a-rails-app-to-a-vps-using-puppet-and-capistrano/) and adapted my deployment settings to match those in [RevTilt](https://github.com/cyrusstoller/RevTilt/issues). I had to manually go into the production server and generate the binstubs and the errors trying to start the application were resolved.

**Comment by cyrusstoller** [comment]
Which binstubs are you referring to? The system ones for `rbenv` or the ones particular to your rails app bundle?

I've used gardenbed to provision a few servers recently and haven't run into this. Can you share a little more about what you did when you ssh'ed into your server?

Happy to try and get this sorted out.

**Comment by sman591** [comment]
The particular rails app ones. When I attempt to deploy for the first time, Capistrano's log showed an error trying to run `bin/unicorn`.

I unfortunately lost my ssh history from yesterday so I can't look up exactly what I ran, but I followed the blog post pretty closely and copied any deployment/Capistrano files word for word other than the obvious app variables to avoid issues.

I'll try deploying to a different VM and see if I can replicate the error.

**Comment by sman591** [comment]
Yep, same issue occurred on a fresh VM. The relevant error log, occurring when I run `bundle exec cap production deploy`: https://gist.github.com/sman591/b53e115d465bf2fd7e85

I followed the steps on the [blog post](http://www.cyrusstoller.com/2014/12/23/deploying-a-rails-app-to-a-vps-using-puppet-and-capistrano/) exactly.

**Comment by cyrusstoller** [comment]
Interesting. Ok I'm able to reproduce the bug when I use ruby 2.2.x, but I don't get it with ruby 2.1.6. I need to look into this.

**Comment by sman591** [comment]
I solved the issue by adding

```ruby
set :bundle_binstubs, -> { shared_path.join('bin') }
```

to `config/deploy.rb`. Though, I'm not sure if this solves the root issue or not.
